apiVersion: apps/v1
kind: Deployment
metadata: 
  name: basket-deployment
spec: 
  
  replicas: 1
  selector: 
    matchLabels: 
      component: basket
  template: 
    metadata: 
      labels: 
        component: basket
    spec: 
      containers: 
        - 
          image: nwekedevregistry.azurecr.io/basketapi:latest
          name: basketapi
          env:
            - name: "ASPNETCORE_ENVIRONMENT"
              value: "Development"
            - name: "ConnectionStrings__Redis"
              value: "redis-cluster-ip-service:6379"
            - name: "EventBus__HostName"
              value: "rabbitmq-cluster-ip-service"
            - name: "EventBus__UserName"
              value: "guest"
            - name: "EventBus__Password"
              value: "guest"

              
          ports: 
            - 
              containerPort: 80
